apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongodb-service
  namespace: truedesk-ticketing
spec:
  type: NodePort
  ports:
  - name: "http"
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    service: mongo
