apiVersion: v1
kind: Service
metadata:
  labels:
     app: truedesk-ui
  name: truedesk-ui
  namespace: truedesk-ticketing
spec:
  type: LoadBalancer
  ports:
  - name: truedesk-service
    port: 8118
    targetPort: 8118
  selector:
    app: truedesk-ui

